services:
    eureka-server:
        build: eureka-sv
        mem_limit: 512m
        ports:
            - "8761:8761"
        networks:
            - 'e-commerce-network'

    products1:
        build: products
        environment:
            DB_PRODUCTS_URI_DOCKER: jdbc:mysql://mysql-products-db:3306/products_db?serverTimezone=UTC&createDatabaseIfNotExist=true
            DB_USERNAME: root
            DB_PASSWORD: lexmark123
        mem_limit: 512m
        ports:
            - "8079:8080"
        networks:
            - 'e-commerce-network'
        depends_on:
            - mysql-products-db

    products2:
        build: products
        environment:
            DB_PRODUCTS_URI_DOCKER: jdbc:mysql://mysql-products-db:3306/products_db?serverTimezone=UTC&createDatabaseIfNotExist=true
            DB_USERNAME: root
            DB_PASSWORD: lexmark123
        mem_limit: 512m
        ports:
            - "8080:8080"
        networks:
            - 'e-commerce-network'
        depends_on:
            - mysql-products-db

    sales:
        build: sales
        environment:
            DB_SALES_URI_DOCKER: jdbc:mysql://mysql-sales-db:3306/sales_db?serverTimezone=UTC&createDatabaseIfNotExist=true
            DB_USERNAME: root
            DB_PASSWORD: lexmark123
        mem_limit: 512m
        ports:
            - "8082:8082"
        networks:
            - 'e-commerce-network'
        depends_on:
            - mysql-sales-db

    shopping-carts:
        build: shopping-cart
        environment:
            DB_SHOPPING-CARTS_URI_DOCKER: jdbc:mysql://mysql-shopping-carts-db:3306/shopping-carts_db?serverTimezone=UTC&createDatabaseIfNotExist=true
            DB_USERNAME: root
            DB_PASSWORD: lexmark123
        mem_limit: 512m
        ports:
            - "8081:8081"
        networks:
            - 'e-commerce-network'
        depends_on:
            - mysql-shopping-carts-db

    api-gateway:
        build: api-gateway
        mem_limit: 512m
        ports:
            - "443:443"
        networks:
            - 'e-commerce-network'

    config-server:
        build: config-server
        mem_limit: 512m
        ports:
            - "8083:8083"
        networks:
            - 'e-commerce-network'

    mysql-products-db:
        image: mysql:8.3.0
        container_name: mysql-products-db
        environment:
            MYSQL_ROOT_PASSWORD: lexmark123
            MYSQL_DATABASE: products_db
        ports:
            -  "3307:3306"
        networks:
            - 'e-commerce-network'

    mysql-sales-db:
        image: mysql:8.3.0
        container_name: mysql-sales-db
        environment:
            MYSQL_ROOT_PASSWORD: lexmark123
            MYSQL_DATABASE: sales_db
        ports:
            - "3308:3306"
        networks:
            - 'e-commerce-network'

    mysql-shopping-carts-db:
        image: mysql:8.3.0
        container_name: mysql-shopping-carts-db
        environment:
            MYSQL_ROOT_PASSWORD: lexmark123
            MYSQL_DATABASE: shopping-carts_db
        ports:
            - "3309:3306"
        networks:
            - 'e-commerce-network'

networks:
    e-commerce-network: